const types = {
    TOGGLE_LOADING: 'TOGGLE_LOADING',
    TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
    TOGGLE_SIDEBAR_SHOW: 'TOGGLE_SIDEBAR_SHOW',
    TOGGLE_DEVICE: "TOGGLE_DEVICE",
    EXPAND_MENU: 'EXPAND_MENU',
    SWITCH_EFFECT: 'SWITCH_EFFECT',
    LOAD_MENU: 'LOAD_MENU',
    LOAD_CURRENT_MENU: 'LOAD_CURRENT_MENU',
    SET_USER_INFO: 'SET_USER_INFO',
    PUSH_CACHED_VIEWS: 'PUSH_CACHED_VIEWS', //添加缓存页面，配合keep-alive使用
    DEL_CACHED_VIEWS: 'DEL_CACHED_VIEWS', //删除缓存页面
    DEL_ALL_CACHED_VIEWS: 'DEL_ALL_CACHED_VIEWS', //删除所有缓存页面
    SET_PERMISSIONS: 'SET_PERMISSIONS', //权限资源
    SET_DICTS: 'SET_DICTS' //数据字典
}

export default types